### ISSUE TITLE
可以增加 播放列表等、搜索歌曲、歌单等功能吗，如图所示~

### ISSUE THREAD

**Issue by huaimi123** [zanjie1999/workdayAlarmClockGo#2]
![1](https://github.com/zanjie1999/workdayAlarmClockGo/assets/131643111/46e19fba-5059-4aa7-ad51-d4a00d1290af)
![2](https://github.com/zanjie1999/workdayAlarmClockGo/assets/131643111/c4926ce3-270b-40df-933c-cf5970ab7897)

https://github.com/xfmujie/musicBox
可以试试此项目的webUI

**Comment by zanjie1999** [comment]
那你为什么不把要放的歌曲放到指定的歌单里，再把那个歌单设置成默认歌单，这样只需按一下音响按钮就能播放，多方便啊，
还一个个搜索那不是脱裤子放屁吗
